name: Setup Environment
description: 'Sets up the necessary tools to build a C/C++ project using CMake and Ninja'

inputs:
  os:
    required: true
    description: 'The os to setup the environment for'

runs:
  using: 'composite'
  steps:
    - name: Setup Windows Environment
      if: contains(inputs.os, 'windows')
      uses: ./.github/actions/setup-windows
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
    - name: Setup Ninja
      uses: cmelchior/setup-ninja@master