name: Setup Windows Build Environment
description: 'Sets up the necessary tools to build a C/C++ project using CMake and Ninja on Windows'

runs:
  using: 'composite'
  steps:
    - name: Install VC tools
      shell: pwsh
      run: choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --norestart --wait --quiet"
    - name: Setup VC Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        vsversion: 2022